const $=id=>document.getElementById(id),api=window.studio;
let state={docs:[],active:null},panes=new Map(),outputs=new Map(),statuses=new Map(),errorLines=new Map(),fontSize=14,noticeTimer;
const current=()=>panes.get(state.active);
function notice(error){$('notice').textContent=error.message||String(error);$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,7000);}
async function call(name,arg){try{return await api.call(name,arg);}catch(e){notice(e);throw e;}}
async function commit(){const p=current();if(p)await call('update',{id:state.active,text:p.area.value});}
function position(){const p=current();if(!p)return;const before=p.area.value.slice(0,p.area.selectionStart);$('position').textContent=`Ln ${before.split('\n').length}, Col ${before.length-before.lastIndexOf('\n')} · ${p.area.value.length} characters`;}
function showConsole(){const d=state.docs.find(d=>d.id===state.active);$('output').textContent=outputs.get(state.active)||'';$('runStatus').textContent=statuses.get(state.active)||'Ready';const running=!!d?.running;for(const name of ['stop','programInput','sendInput','endInput'])$(name).disabled=!running;$('run').disabled=running;$('clear').disabled=running;$('error').disabled=!errorLines.get(state.active);}
function theme(){document.body.dataset.theme=state.dark?'dark':'light';$('guideFrame').contentWindow?.postMessage({studioTheme:state.dark?'dark':'light'},'*');}
function colorize(p){if(p.coloredText!==p.area.value){p.paint.innerHTML=FiMSyntax.html(p.area.value);p.coloredText=p.area.value;}p.paint.scrollTop=p.area.scrollTop;p.paint.scrollLeft=p.area.scrollLeft;}
function render(next){state=next;if(Number.isFinite(next.fontSize))fontSize=next.fontSize;document.documentElement.style.setProperty('--font-size',fontSize+'px');
 for(const [id,p] of panes)if(!state.docs.some(d=>d.id===id)){p.root.remove();panes.delete(id);outputs.delete(id);statuses.delete(id);errorLines.delete(id);}
 for(const d of state.docs){let p=panes.get(d.id);if(!p){const root=document.createElement('div');root.className='editor-pane';const gutter=document.createElement('pre');gutter.className='gutter';gutter.setAttribute('aria-hidden','true');const area=document.createElement('textarea');area.className='source';area.wrap='off';area.spellcheck=false;area.setAttribute('aria-label','FiM++ source editor');area.autocapitalize='off';area.autocomplete='off';area.value=d.text;const surface=document.createElement('div');surface.className='source-surface';const paint=document.createElement('pre');paint.className='syntax-paint';paint.setAttribute('aria-hidden','true');surface.append(paint,area);root.append(gutter,surface);$('editors').append(root);p={root,gutter,area,paint};panes.set(d.id,p);
 area.addEventListener('input',()=>{const doc=state.docs.find(x=>x.id===d.id);doc.text=area.value;doc.dirty=true;colorize(p);gutter.textContent=Array.from({length:area.value.split('\n').length},(_,i)=>i+1).join('\n');call('update',{id:d.id,text:area.value}).catch(()=>{});renderTabs();position();});
 area.addEventListener('scroll',()=>{gutter.scrollTop=area.scrollTop;colorize(p);});['keyup','click','select'].forEach(e=>area.addEventListener(e,position));
 area.addEventListener('keydown',event=>{if(event.key==='Tab'){event.preventDefault();document.execCommand('insertText',false,'    ');}if(event.key==='Enter'&&!event.ctrlKey&&!event.metaKey){event.preventDefault();const start=area.value.lastIndexOf('\n',area.selectionStart-1)+1;const line=area.value.slice(start,area.selectionStart);let indent=line.match(/^\s*/)[0];if(/^(?:\s*)(?:I learned|Today I learned|When |I did this|In the end, I did this instead|It didn't work, but I knew why)/i.test(line))indent+='    ';document.execCommand('insertText',false,'\n'+indent);}});
 }
 if(p.area.value!==d.text)p.area.value=d.text;p.gutter.textContent=Array.from({length:d.text.split('\n').length},(_,i)=>i+1).join('\n');p.root.hidden=d.id!==state.active;colorize(p);
 }
 renderTabs();showConsole();theme();position();}
function renderTabs(){$('tabs').replaceChildren();for(const d of state.docs){const item=document.createElement('div');item.className='tab'+(d.id===state.active?' active':'');const select=document.createElement('button');select.textContent=(d.dirty?'● ':'')+d.name;select.title=d.file||d.name;select.onclick=async()=>{await commit();await call('activate',d.id);current()?.area.focus();};const close=document.createElement('button');close.className='close';close.textContent='×';close.setAttribute('aria-label','Close '+d.name);close.onclick=async()=>{await commit();await call('close',d.id);};item.append(select,close);$('tabs').append(item);}}
function goError(){const p=current(),line=errorLines.get(state.active);if(!p||!line)return;const lines=p.area.value.split('\n');const start=lines.slice(0,line-1).join('\n').length+(line>1?1:0);p.area.focus();p.area.setSelectionRange(start,start+(lines[line-1]?.length||0));p.area.scrollTop=Math.max(0,(line-3)*fontSize*1.65);position();}
function findNext(){const p=current(),needle=$('findText').value;if(!p||!needle)return false;let at=p.area.value.indexOf(needle,p.area.selectionEnd);if(at<0)at=p.area.value.indexOf(needle);$('findResult').textContent=at<0?'Not found':'';if(at<0)return false;p.area.focus();p.area.setSelectionRange(at,at+needle.length);p.area.scrollTop=Math.max(0,(p.area.value.slice(0,at).split('\n').length-3)*fontSize*1.65);position();return true;}
async function act(name){try{await commit();if(name.startsWith('example:'))return await call('example',name.slice(8));switch(name){case'new':case'open':await call(name);current()?.area.focus();break;case'save':case'saveAs':case'close':case'stop':await call(name,state.active);break;case'run':await call('run',state.active);break;case'guide':$('reference').hidden=!$('reference').hidden;break;case'guideShow':$('reference').hidden=false;break;case'find':$('findbar').hidden=false;$('findText').focus();break;case'error':goError();break;case'larger':case'smaller':fontSize=Math.max(10,Math.min(40,fontSize+(name==='larger'?1:-1)));document.documentElement.style.setProperty('--font-size',fontSize+'px');await call('fontSize',fontSize);break;}}catch{}}
for(const name of ['run','stop','guide','error','larger','smaller'])$(name).onclick=()=>act(name);
$('examples').onchange=async()=>{const value=$('examples').value;$('examples').value='';if(value)await act('example:'+value);};
$('clear').onclick=()=>{outputs.set(state.active,'');showConsole();};
$('inputForm').onsubmit=event=>{event.preventDefault();call('input',{id:state.active,text:$('programInput').value}).then(()=>$('programInput').value='').catch(()=>{});};
$('endInput').onclick=()=>{call('eof',state.active).catch(()=>{});$('programInput').disabled=$('sendInput').disabled=$('endInput').disabled=true;};
$('findNext').onclick=findNext;$('findText').onkeydown=e=>{if(e.key==='Enter')findNext();if(e.key==='Escape')$('findbar').hidden=true;};$('closeFind').onclick=()=>{$('findbar').hidden=true;current()?.area.focus();};
$('replaceOne').onclick=()=>{const p=current();if(!p)return;if(p.area.value.slice(p.area.selectionStart,p.area.selectionEnd)!==$('findText').value&&!findNext())return;p.area.focus();document.execCommand('insertText',false,$('replaceText').value);};
$('replaceAll').onclick=()=>{const p=current(),needle=$('findText').value;if(!p||!needle)return;const result=p.area.value.split(needle).join($('replaceText').value);p.area.focus();p.area.select();document.execCommand('insertText',false,result);};
$('guideFrame').onload=theme;
api.on('state',render);api.on('command',act);
api.on('started',({id})=>{outputs.set(id,'');statuses.set(id,'Running');errorLines.delete(id);showConsole();});
api.on('output',({id,text})=>{outputs.set(id,(outputs.get(id)||'')+text);if(id===state.active){$('output').textContent=outputs.get(id);$('output').scrollTop=$('output').scrollHeight;}});
api.on('ended',({id,status,errorLine})=>{statuses.set(id,status);errorLines.set(id,errorLine);showConsole();});
call('init').then(initial=>{for(const e of initial.catalog){const option=document.createElement('option');option.value=e.file;option.textContent=e.title;$('examples').append(option);}$('guideFrame').src=initial.guide;render(initial);current()?.area.focus();});
