const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {execFile}=require('node:child_process');const {promisify}=require('node:util');const exec=promisify(execFile);
const {LetterRunner}=require('./runner.cjs');
async function selfTest({resourceRoot,java,jar,args}){
 const report={platform:process.platform,architecture:process.arch,version:'1.2.4',passed:[],failures:[]};
 const outputArg=args.find(a=>a.startsWith('--report='));const reportPath=outputArg?outputArg.slice(9):path.join(require('node:os').tmpdir(),'FiM-Studio-Windows-validation.json');
 const check=async(name,fn)=>{try{await fn();report.passed.push(name);}catch(e){report.failures.push({name,error:e.message});}};
 await check('Syntax coloring and protected comments/strings',async()=>{const {tokens,html}=require('./syntax.js');assert.deepEqual(tokens('I said "P.S. (42)".\nPSS comment').map(t=>t.kind),['keyword','string','comment']);assert(!html('"<script>"').includes('<script>'));});
 await check('Editor colors, themes, alignment, scrolling and undo',async()=>{report.editor=await require('./editor-test.cjs').editorTest();});
 await check('Compiler SHA-256' ,async()=>{const expected=JSON.parse(await fs.readFile(path.join(resourceRoot,'Validation/expected.json'),'utf8'));assert.equal(crypto.createHash('sha256').update(await fs.readFile(jar)).digest('hex'),expected.compiler);});
 await check('20 examples and renamed interpreter',async()=>{const c=JSON.parse(await fs.readFile(path.join(resourceRoot,'Examples/catalog.json'),'utf8'));assert.equal(c.length,20);assert.equal(c.find(e=>e.file==='bf').title,'Brainf*** interpreter');for(const e of c)await fs.access(path.join(resourceRoot,'Examples',e.file+'.fimpp'));});
 await check('Offline guide and Windows shortcuts',async()=>{const g=await fs.readFile(path.join(resourceRoot,'Guide/index.html'),'utf8');assert(g.includes('Ctrl+R'));assert(g.includes('Brainf*** interpreter'));assert(g.includes('Created by: RyogaTwo'));});
 await check('322 compiler reference cases',async()=>{const expected=JSON.parse(await fs.readFile(path.join(resourceRoot,'Validation/expected.json'),'utf8'));const cp=[jar,path.join(resourceRoot,'Validation')].join(path.delimiter);const {stdout}=await exec(java,['-Djava.awt.headless=true','-Dfile.encoding=UTF-8','-cp',cp,'ReferenceRunner',path.join(resourceRoot,'Validation/input.tsv')],{windowsHide:true,timeout:180000,maxBuffer:8*1024*1024});const results=new Map(stdout.trim().split(/\r?\n/).map(line=>{const [id,status,out]=line.split('\t');return[id,{status,text:Buffer.from(out,'base64').toString('utf8').replaceAll('\r\n','\n')}];}));for(const c of expected.cases){assert.deepEqual(results.get(c.id),{status:c.expected_status,text:c.expected},c.name);}report.referenceCasesPassed=expected.cases.length;});
 const run=(text,input,stop=false)=>new Promise((resolve,reject)=>{let output='';const runner=new LetterRunner({java,jar,onOutput:s=>output+=s,onEnd:r=>resolve({...r,output})});const timer=setTimeout(()=>{runner.stop();reject(Error('Timed out'));},15000);runner.onEnd=r=>{clearTimeout(timer);resolve({...r,output});};runner.start(text).then(()=>{if(input!==undefined){runner.input(input);runner.eof();}if(stop)setTimeout(()=>runner.stop(),500);}).catch(reject);});
 await check('Runner Hello',async()=>{const r=await run(await fs.readFile(path.join(resourceRoot,'Examples/hello.fimpp'),'utf8'));assert.equal(r.status,'Finished');assert(r.output.includes('Hello, Equestria'));});
 await check('Program input',async()=>{const r=await run(await fs.readFile(path.join(resourceRoot,'Examples/input.fimpp'),'utf8'),'Rainbow Dash');assert.equal(r.status,'Finished');assert(r.output.includes('Hello, Rainbow Dash!'));});
 await check('Stop process tree',async()=>{const r=await run('Dear Princess Celestia: Test.\nToday I learned:\nI did this while 1 is equal to 1:\nBy the way, Waiting.\nThat\'s what I did.\nYour faithful student, Twilight Sparkle.\n',undefined,true);assert.equal(r.status,'Stopped');});
 await check('Error location',async()=>{const r=await run('Dear Princess Celestia: Test.\nToday I learned:\nInvalid code.\nYour faithful student, Twilight Sparkle.');assert.equal(r.status,'Check output');assert.equal(r.errorLine,3);});
 report.javaVersion=(await exec(java,['-version'],{windowsHide:true})).stderr.trim();report.success=report.failures.length===0;await fs.mkdir(path.dirname(reportPath),{recursive:true});await fs.writeFile(reportPath,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(!report.success)throw Error('Self-test failed: '+reportPath);
}
module.exports={selfTest};
